### ISSUE TITLE
Improve QEMU monitor protocol

### ISSUE THREAD

**Issue by noxdafox** [KVM-VMI/qemu#1]
During a discussion @pfohjo mentioned the idea of providing a binary QEMU protocol to improve performance when delivering the Events.

QEMU monitor protocol introduces the overhead of serializing and de-serializing into JSON every single message which is detrimental for our use case.

Maybe the monitor protocol could then be re-built on top of the binary one?

[XDR](https://en.wikipedia.org/wiki/External_Data_Representation) could be a good protocol for example.

**Comment by Wenzel** [comment]
Hi @noxdafox,

considering the progress we have made with the `kvmi` subsystem, i'm closing this issue.
Feel to reopen it if you want to continue the discussion nonetheless.
