### ISSUE TITLE
Problems with memory-access.h and memory-access.c

### ISSUE THREAD

**Issue by TheLostBoy2020** [KVM-VMI/qemu#6]
In the file called memory-access.h it is mentioned that fuse takes care to mount the guest memory. I have already built the qemu-system - ***, and it creates the domain socket for me when I type the pmemaccess command, and bind it with volatility so that the socket can be exposed. But, I occupy the socat and I don't see the data flow that should go through the socket.

Also occupy the socat without occupying the volatility since the socket created disappears. and the result is the same.

My question is: is there a way to build QEMU but does it recognize fuse? I have installed KALI 2020.3 and it already has fuse (libfuse)

Or what would I miss so that I can see the memory of the guest?

Thanks for your time and response.

**Comment by Wenzel** [comment]
Hi @TheLostBoy2020, with `memory-access.*` patches, you are referencing a memory introspection method used by `LibVMI` with custom memory access patches for QEMU.

This method is deprecated by the KVM-VMI project, in favor of the KVMi subsystem built by Bitdefender.
You can find the Setup guide here:
https://kvm-vmi.github.io/kvm-vmi/master/setup.html

I think your question would better be addressed in the LibVMI repository, if you don't mind opening an issue there, I'm sure Tamas will answer you.

About FUSE, Libvmi has a tool named [vmifs](https://github.com/libvmi/libvmi/blob/master/tools/vmifs/vmifs.c) which is based on FUSE to mount the guest memory as a file.
I think the comment about FUSE in memory-access.h is just legacy comment that should be removed.

**Comment by TheLostBoy2020** [comment]
Hi Wenzel,

Thank you for your time in answering my question quickly, and I will put my question in the LibVMI repository and wait for the answer from Tamas.

   I'm going to test the vmifs tool, and you're right, it would be better to remove that comment in the future.

Thanks for everything!!!
